[package]
name = "zorro_chess"
version = "0.0.0"
edition = "2018"

[dependencies]
bitintr = "0.3"
enum-map = "0.6"
enum-map-derive = "0.4"
lazy_static = "1"
rand = "0.7"
strum = "0.15.0"
strum_macros = "0.15.0"
zorro_common = { path = "../common" }
